"use client"
import './globals.css';
import { useEffect, ReactNode } from 'react';
import Inter  from 'next/font/google';

export const metadata = {
  title: 'Worqhat-TxtToCode',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: ReactNode;
}

const RootLayout = ({ children }: RootLayoutProps) => {
  useEffect(() => {
    const linkElement = document.createElement('link');
    linkElement.href =
      'https://fonts.googleapis.com/css2?family=Inter:wght@400;500&display=swap';
    linkElement.rel = 'stylesheet';

    document.head.appendChild(linkElement);
  }, []);

  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
};


export default RootLayout;
